### PR TITLE
RAW Video - added 60 and 120 FPS options, increased RAM limit

### PR DESCRIPTION
**Pull request by epicfilmmaker93**
There are asterisks because you will need at least 3GB of RAM to run 4K 21:9 RAW Video at 60 FPS, and it will only be enough for about 4 seconds. If your device has a lot of RAM (8 or more GB), you can try increasing the limit to 4GB to improve the performance. 120 fps may not work without binning because as far as I understand MotionCam always requests full resolution RAW from the API, and some devices are capable of 120 only at 16:9 crop (you can try yourself with custom profile in FreeDCam)

And happy holidays everyone!

### CODE REVIEW

**Comment by epicfilmmaker93** [comment]
Edit: tested and it doesn't seem to work, sorry

**Comment by epicfilmmaker93** [comment]
Edit2: and now it works for some reason? Anyway, will wait for @mirsadm

**Comment by mirsadm** [comment]
Will take a look. On my phone at least I don't think I can get more than 30 fps

**Comment by experimentator1709** [comment]
@mirsadm 
I have 1+ 8 pro. I am ready to test 60 frames per second and more. He can.

**Comment by epicfilmmaker93** [comment]
I confirm that my device is capable of 4K120 (at least in video mode) with a 16:9 crop, but if I use the full sensor, the maximum framerate seems to be 96. I found these two settings which might help to read only a part of the sensor and make 120fps possible while also decreasing the amount of needed RAM:
https://developer.android.com/reference/android/hardware/camera2/CaptureRequest#SCALER_CROP_REGION
https://developer.android.com/reference/android/hardware/camera2/CaptureRequest#CONTROL_ZOOM_RATIO

**Comment by epicfilmmaker93** [comment]
Also, FreeDCam now also has RAW Video if you compile it from Git. Currently it seems to be limited to full resolution at 30 fps and records for about 5 seconds then crashes (MotionCam records for 10 seconds with the same settings). FreeDCam has an option to choose a cropped resolution, but it doesn't work on my device for some reason. I don't know what API settings FreeDCam uses but I think you guys should cooperate @mirsadm @KillerInk

**Comment by mirsadm** [comment]
Any help is always appreciated. MotionCam is written mostly in C++ which, I think, makes it different to most other apps. It will be very difficult to ensure good performance in Java

**Comment by KillerInk** [comment]
indeed its incredible what you are doing.
but no its not difficult to ensure good perfomance in java^^
only thing you should avoid is to swap big memory between native and java.
greets

**Comment by mirsadm** [comment]
> Also, FreeDCam now also has RAW Video if you compile it from Git. Currently it seems to be limited to full resolution at 30 fps and records for about 5 seconds then crashes (MotionCam records for 10 seconds with the same settings). FreeDCam has an option to choose a cropped resolution, but it doesn't work on my device for some reason. I don't know what API settings FreeDCam uses but I think you guys should cooperate @mirsadm @KillerInk

It's not possible to crop the sensor in the way you think it is. From the Android API documentation:

The crop region is applied after the RAW to other color space (e.g. YUV) conversion. Since raw streams (e.g. RAW16) don't have the conversion stage, they are not croppable. The crop region will be ignored by raw streams.

I crop the data after it has been captured. That code has to run very fast otherwise it's not worth doing. Under 33 ms for 30 FPS and under 8 ms for 120 FPS.

**Comment by epicfilmmaker93** [comment]
Well, I'm sorry then, that's disappointing. So no RAW slow motion of any kind then?

Also, should I reopen this PR? 60 definitely works for me, and people with the newest Xperias may try 120

**Comment by mirsadm** [comment]
Well I wouldn't say that. Hardware is getting faster and faster. I'll add in the extra FPS options soon

**Comment by epicfilmmaker93** [comment]
Is it possible to offload the processing to the GPU?

And please add a disclaimer for 60 and 120 fps options when you add them so that people know these options may not necessarily work

**Comment by mirsadm** [comment]
I'll add them in at the bottom as experimental for now. I'm looking at some faster real time compression options now. Ideally if I could access the DSP on Snapdragon phones it would be very beneficial. It seems to be locked down for some reason.

**Comment by epicfilmmaker93** [comment]
>I'll add them in at the bottom as experimental for now. 
Good idea

I think you are talking about the Hexagon DSP, here is their SDK page:
https://developer.qualcomm.com/software/hexagon-dsp-sdk
Google Camera seems to use it, so you might want to ask its ports devs for help

**Comment by ishansd94** [comment]
I got in touch with https://forum.xda-developers.com/m/beserker15.2038895/. @mirsadm maybe you can contact him regarding the exact issue.

**Comment by epicfilmmaker93** [comment]
Hijacking this thread to talk about performance. I've installed a custom kernel and now I am sometimes able to record 4K 21:9 100p in MotionCam for 10 seconds, and if I use the latest FreeDCam with manually edited RawRecordApi2, I seem to get 30 seconds of 4K 21:9 120p (probably with frame drops), which is more than 4000 frames. So good job guys, I think the performance will be even better on 2022 phones

**Comment by mirsadm** [comment]
Is that 100 FPS for 10 seconds? There's plenty of performance left of the table still. I'm looking at a much better compression schemes at the moment as an example. Why I'm hesitant to write directly to DNG it would prevent me from doing that. I'd be surprised if you were able to get usable footage at that frame rate from FreeDCAM because it is a lot of data.

**Comment by epicfilmmaker93** [comment]
Yes, 5-10 seconds of 3884x1666 at 100p with MotionCam (I've edited the XML to get the 100p option the same way as in this PR). Will drop frames if the shutter speed is 1/100, but 1/125 works fine. The I/O scheduler that works best for me is noop

FreeDCam drops frames but I get at least 30p at the same resolution for 5-30 seconds, can't figure out the exact framerate right now

**Comment by mirsadm** [comment]
I think if things work out the way I'm hoping I should be able to get 2:1 compression at least which should make possible to do 120 FPS at that resolution on fast storage (~500 mb/sec). Or splitting writing between internal and external which already exists in the app but is disabled for now

**Comment by epicfilmmaker93** [comment]
>2:1 compression at least which should make possible to do 120 FPS at that resolution on fast storage (~500 mb/sec).

That would be really great

>Or splitting writing between internal and external which already exists in the app but is disabled for now

Also good idea, I now have an external SSD so I am ready to test that

>with your 100 FPS testing are you getting 100 FPS without dropped frames with MotionCam?

Yes, 100p without dropped frames, but only for 10 seconds at best

**Comment by KillerInk** [comment]
> I've made a mistake again, sorry, FreeDCam definetely drops frames.

Well lets put things together. 
with a shutter speed 1/30 you get 30fps.
with 1/60 60fps.
with 1/100 100fps. (not on my phone, there it seems to be limited to 60fps)
so with using a fixed shutter speed that match the recording fps, the finaly movie will have the correct fps.
but there is also an auto mode wich can change the shutter speed depending on light situation.
due that my approach trys to save out at constant 25 fps also if your shutter speed is set to1/100 and return 100fps.
when it realy drop frames, you see it in the file names that the numbers are not continouse written.

From code side it looks like this:
image reader is set to preview stream and feeds a ringbuffer.
a consumer thread takes every 1/25sec a frame from the ringbuffer and feed it to a savingqueue.
if the queue is full, the frame get dropped.

greets

**Comment by epicfilmmaker93** [comment]
I've spent some more time tuning the kernel settings and I think I broke something - now there are black frames in the video. Could you please tell me where the problem might be?

**Comment by experimentator1709** [comment]
@mirsadm 
Where can I download the 60 FPS version?

**Comment by epicfilmmaker93** [comment]
Not @mirsadm but you can merge this pull request locally and compile the app. You will need a Linux machine to run setupenv.sh to get all the needed dependencies. Or you can just wait until higher framerate modes get added officially

**Comment by mirsadm** [comment]
There's a new beta release which has more frame rate options

**Comment by epicfilmmaker93** [comment]
Thank you for the update, I now get more than 2000 frames of 4K 21:9 120p without frame drops

**Comment by experimentator1709** [comment]
I recorded on 1+ 8 pro - 4000x3000 60fps without any problems. But 120fps writes only 30fps on any crop...

**Pull request closed without merging**
